project:
  type: website
  output-dir: docs
  resources:
    - files/*.pdf
    - files/*.jpg
    - files/figures/*
    - .nojekyll

website:
  title: "Fernando Hoces de la Guardia"
  site-url: https://fhoces.github.io
  navbar:
    left:
      - href: research.qmd
        text: Research
      - href: policy.qmd
        text: Policy
      - href: teaching.qmd
        text: Teaching and Learning
      - href: cv.qmd
        text: CV and Resume
    right:
      - icon: github
        href: https://github.com/fhoces
        aria-label: GitHub
      - icon: envelope
        href: mailto:fhoces@berkeley.edu
        aria-label: Email
  page-footer:
    center: "© 2026 Fernando Hoces de la Guardia"

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: false
    smooth-scroll: true
